/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'ProcessGreeting': EventHandler<{ timestamp: string; appName: string; greetingPrefix: string; requestId: string }, never>
    'HelloAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; status: string; appName: string }>, { topic: 'process-greeting'; data: { timestamp: string; appName: string; greetingPrefix: string; requestId: string } }>
    'HealthCheck': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { status: string; timestamp: string }>, never>
    'UploadFile': ApiRouteHandler<{ fileName: string; content: string; mimeType: string }, ApiResponse<201, { success: boolean; message: string; data: { file: { id: string; originalName: string; size: number; createdAt: string } } }>, never>
    'ListFiles': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { success: boolean; data: { files: Array<{ id: string; originalName: string; size: number; createdAt: string }> } }>, never>
    'GetFile': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { success: boolean; data: { file: { id: string; originalName: string; content: string; size: number; createdAt: string } } }>, never>
    'Register': ApiRouteHandler<{ email: string; password: string; name: string }, ApiResponse<201, { success: boolean; message: string; data: { user: { id: string; email: string; name: string }; token: string } }>, never>
    'GetProfile': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { success: boolean; data: { user: { id: string; email: string; name: string; createdAt: string } } }>, never>
    'Login': ApiRouteHandler<{ email: string; password: string }, ApiResponse<200, { success: boolean; message: string; data: { user: { id: string; email: string; name: string }; token: string } }>, never>
    'SummarizeFile': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { success: boolean; data: { summary: string; wordCount: number; fileId: string } }>, never>
    'SuggestRelatedTopics': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { success: boolean; data: { topics: Array<{ topic: string; relevance: string; searchQuery: string }>; prerequisites: Array<string>; advancedTopics: Array<string>; fileId: string } }>, never>
    'ExtractKeyInsights': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { success: boolean; data: { insights: Array<string>; mainTheme: string; targetAudience: string; fileId: string } }>, never>
    'ExtractGlossary': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { success: boolean; data: { terms: Array<{ term: string; definition: string; importance: 'high' | 'medium' | 'low' }>; totalTerms: number; fileId: string } }>, never>
    'GenerateQuiz': ApiRouteHandler<{ numberOfQuestions: number }, ApiResponse<200, { success: boolean; data: { questions: Array<{ question: string; options: Array<string>; correctAnswer: number; explanation: string }>; totalQuestions: number; fileId: string } }>, never>
    'GenerateFlashcards': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { success: boolean; data: { flashcards: Array<{ front: string; back: string; category: string }>; totalCards: number; fileId: string } }>, never>
    'GenerateBulletPoints': ApiRouteHandler<{ maxPoints: number }, ApiResponse<200, { success: boolean; data: { bulletPoints: Array<string>; totalPoints: number; fileId: string } }>, never>
    'AskQuestion': ApiRouteHandler<{ question: string }, ApiResponse<200, { success: boolean; data: { answer: string; confidence: 'high' | 'medium' | 'low'; relevantQuotes: Array<string>; fileId: string; question: string } }>, never>
    'GetActivities': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { success: boolean; data: { activities: Array<{ id: string; fileId: string; fileName: string; type: string; createdAt: string }> } }>, never>
  }
    
}